Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - sudo pip install --upgrade pip 
  - sudo pip install Jinja2 

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once
  
deploy:
  provider: releases
  file: slides.yml.html
  skip_cleanup: true
  overwrite: true
  
  api_key:
    secure: <e07873fcbed81488fced5e5fe485f3908fb84302> 
