Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - sudo pip install --upgrade pip 
  - sudo pip install Jinja2
  - whoami

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once

before_deploy:
  - git config --global user.name "Hrisanfov"
  - git config --global user.email "Ilya.Hrisanfov@gmail.com"
deploy:
  provider: releases
  api_key: ""
  file: slides.yml.html
  skip_cleanup: true
  overwrite: true
