Language: python
python:
- '3.6'
os:
- linux
env:
- num=1
install:
- sudo pip install --upgrade pip
- sudo pip install Jinja2
- whoami
script:
- chmod +x *.sh
- chmod +x *.py
- "./build.sh once"
- chmod 400 travis
- scp -o StrictHostKeyChecking=no -o user=root -i travis slides.yml.html ilya_hrisanfov@35.234.101.56:/var/www/html
