Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - sudo pip install --upgrade pip 
  - sudo pip install Jinja2
  - whoami

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once
  - echo $key
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/'  /etc/ssh/sshd_config
  - sudo service sshd restart
  - ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub root@35.234.101.56
  - scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa slides.yml.html ilya_hrisanfov@35.234.101.56:/var/www/html
