Language: python
python:
- '3.6'
os:
- linux
env:
- num=1
before_install:
- openssl aes-256-cbc -K $encrypted_c83d1e291deb_key -iv $encrypted_c83d1e291deb_iv
  -in travis.enc -out travis -d
install:
- sudo pip install --upgrade pip
- sudo pip install Jinja2
- whoami
script:
- chmod +x *.sh
- chmod +x *.py
- "./build.sh once"
- chmod 400 id_rsa
- scp -o StrictHostKeyChecking=no -o user=root -i travis slides.yml.html ilya_hrisanfov@35.234.101.56:/var/www/html
