Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - sudo pip install --upgrade pip 
  - sudo pip install Jinja2 

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once
  
deploy:
  provider: releases
  api_key: 60bcb44002c1f26c6a4f601dbaf960cad8e6e5c5
  file: slides.yml.html
  skip_cleanup: true
  overwrite: true
