Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - sudo pip install --upgrade pip 
  - sudo pip install Jinja2
  - whoami

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once
  - echo $key
  - echo $key >> ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - ssh -oStrictHostKeyChecking=no -N "" root@35.234.101.56
