Language: python
python: 
  - "3.6"
os:
  - linux

env:
  - num=1

install:
  - pip install --upgrade pip --user Hrisanfov
  - pip install Jinja2 --user Hrisanfov

script:
  - chmod +x *.sh
  - chmod +x *.py
  - ./build.sh once

